"""FastVQ public import alias.

The distribution is published as ``fastvq``. The implementation package remains
``turboquant`` for compatibility with existing code.
"""

from turboquant import (
    QJL,
    PolarQuant,
    TurboQuant,
    TurboQuantConfig,
    TurboQuantGGUFLoader,
    TurboQuantSafeTensorsLoader,
    __author__,
    __version__,
    benchmark_array,
    compute_distortion,
    compute_mse,
    export_to_gguf,
    export_to_safetensors,
    generate_codebook,
    get_lloyd_max_codebook,
    load_gguf,
    load_gguf_model,
    load_model,
    load_safetensors,
    load_safetensors_model,
    make_dataset,
    parse_shape,
    parse_shapes,
    quantize_decompress_benchmark,
    quantize_model_weights,
    run_benchmark_suite,
    write_benchmark_results,
)

__all__ = [
    "TurboQuant",
    "TurboQuantConfig",
    "PolarQuant",
    "QJL",
    "get_lloyd_max_codebook",
    "generate_codebook",
    "quantize_decompress_benchmark",
    "compute_mse",
    "compute_distortion",
    "benchmark_array",
    "make_dataset",
    "parse_shape",
    "parse_shapes",
    "run_benchmark_suite",
    "write_benchmark_results",
    "export_to_gguf",
    "export_to_safetensors",
    "load_gguf",
    "load_safetensors",
    "load_gguf_model",
    "load_safetensors_model",
    "load_model",
    "quantize_model_weights",
    "TurboQuantGGUFLoader",
    "TurboQuantSafeTensorsLoader",
    "__author__",
    "__version__",
]
