#!/usr/bin/env python3
"""
Simple TurboQuant API Server (Lightweight Version)
OpenAI-compatible API demonstrating TurboQuant KV cache compression.
"""

import time
import json
import uuid
from pathlib import Path
from typing import Optional, List, Dict, Any

import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse, HTMLResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import uvicorn

from turboquant.kv_cache import KVCacheCompressor, StreamingKVCache


# Data Models
class ChatMessage(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    model: str = "gemma-4-31b"
    messages: List[ChatMessage]
    max_tokens: int = 256
    temperature: float = 0.7
    stream: bool = False
    turboquant_bits: int = Field(default=3, ge=2, le=4)


class TurboQuantStats(BaseModel):
    enabled: bool
    bit_width: int
    compression_ratio: float
    memory_saved_gb: float


# Create app
app = FastAPI(
    title="TurboQuant API",
    description="OpenAI-compatible API with TurboQuant KV cache compression",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global state
kv_cache: Optional[StreamingKVCache] = None
compressor: Optional[KVCacheCompressor] = None
model_path: Optional[Path] = None


def format_messages(messages: List[ChatMessage]) -> str:
    """Format messages to prompt."""
    parts = []
    for msg in messages:
        if msg.role == "system":
            parts.append(f"System: {msg.content}\n")
        elif msg.role == "user":
            parts.append(f"User: {msg.content}\n")
        else:
            parts.append(f"Assistant: {msg.content}\n")
    parts.append("Assistant: ")
    return "".join(parts)


def generate_response(prompt: str, max_tokens: int, bits: int) -> str:
    """Generate simulated response with TurboQuant KV cache."""
    global kv_cache

    # Initialize cache if needed
    if kv_cache is None or kv_cache.compressor.config.bit_width != bits:
        kv_cache = StreamingKVCache(bit_width=bits, block_size=128)

    # Simulate token generation with KV cache updates
    tokens_to_generate = min(max_tokens, 100)  # Limit for demo

    for i in range(tokens_to_generate):
        # Simulate KV cache update for each token
        k_new = np.random.randn(1, 8, 1, 128).astype(np.float32) * 0.01
        v_new = np.random.randn(1, 8, 1, 128).astype(np.float32) * 0.01
        kv_cache.append(k_new, v_new)

    # Generate response based on prompt keywords
    prompt_lower = prompt.lower()
    if "quantum" in prompt_lower:
        response = """Quantum computing uses quantum bits (qubits) that can exist in superposition, unlike classical bits that are either 0 or 1. This allows quantum computers to perform certain calculations exponentially faster than classical computers for specific problems like factorization and quantum simulation."""
    elif "hello" in prompt_lower or "hi" in prompt_lower:
        response = (
            "Hello! I'm running with TurboQuant KV cache compression. How can I help you today?"
        )
    elif "2+2" in prompt_lower or "math" in prompt_lower:
        response = "2 + 2 = 4. The calculation is straightforward arithmetic!"
    else:
        response = f"This is a simulated response using TurboQuant {bits}-bit KV cache compression. In a full deployment with llama-cpp-python, this would be generated by the Gemma 4 31B model. The API is fully OpenAI-compatible and supports streaming responses."

    return response


@app.get("/")
async def root():
    """Root endpoint."""
    return {
        "name": "TurboQuant API",
        "version": "0.1.0",
        "turboquant": {"enabled": True, "kv_cache": kv_cache is not None},
        "endpoints": {
            "chat": "/v1/chat/completions",
            "models": "/v1/models",
            "stats": "/v1/turboquant/stats",
            "ui": "/ui",
            "health": "/health",
        },
    }


@app.get("/health")
async def health():
    """Health check."""
    return {
        "status": "healthy",
        "turboquant_enabled": True,
        "model_loaded": model_path is not None,
    }


@app.get("/v1/models")
async def list_models():
    """List models."""
    return {
        "object": "list",
        "data": [
            {
                "id": "gemma-4-31b",
                "object": "model",
                "owned_by": "turboquant",
                "ready": True,
                "turboquant_enabled": True,
            }
        ],
    }


@app.get("/v1/turboquant/stats")
async def get_stats():
    """Get TurboQuant statistics."""
    global compressor

    if compressor is None:
        compressor = KVCacheCompressor(bit_width=3)

    stats = compressor.compute_memory_stats(seq_len=4096, n_heads=8, head_dim=128)

    return {
        "enabled": True,
        "bit_width": 3,
        "compression_ratio": stats["compression_ratio"],
        "memory_saved_gb": stats["memory_saved_gb"],
        "kv_cache_entries": kv_cache.seq_len if kv_cache else 0,
    }


@app.post("/v1/chat/completions")
async def chat_completions(request: ChatRequest):
    """Chat completions endpoint."""
    prompt = format_messages(request.messages)

    if request.stream:
        # Streaming response
        async def stream_generator():
            completion_id = f"chatcmpl-{uuid.uuid4().hex[:12]}"
            created = int(time.time())

            # Initial chunk
            initial = {
                "id": completion_id,
                "object": "chat.completion.chunk",
                "created": created,
                "model": request.model,
                "choices": [{"index": 0, "delta": {"role": "assistant"}, "finish_reason": None}],
            }
            yield f"data: {json.dumps(initial)}\n\n"

            # Generate and stream
            response = generate_response(prompt, request.max_tokens, request.turboquant_bits)
            words = response.split()

            for word in words:
                chunk = {
                    "id": completion_id,
                    "object": "chat.completion.chunk",
                    "created": created,
                    "model": request.model,
                    "choices": [
                        {"index": 0, "delta": {"content": word + " "}, "finish_reason": None}
                    ],
                }
                yield f"data: {json.dumps(chunk)}\n\n"
                time.sleep(0.05)  # Simulate streaming delay

            # Final chunk
            final = {
                "id": completion_id,
                "object": "chat.completion.chunk",
                "created": created,
                "model": request.model,
                "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}],
            }
            yield f"data: {json.dumps(final)}\n\n"
            yield "data: [DONE]\n\n"

        return StreamingResponse(stream_generator(), media_type="text/event-stream")

    else:
        # Non-streaming
        response_text = generate_response(prompt, request.max_tokens, request.turboquant_bits)

        return {
            "id": f"chatcmpl-{uuid.uuid4().hex[:12]}",
            "object": "chat.completion",
            "created": int(time.time()),
            "model": request.model,
            "choices": [
                {
                    "index": 0,
                    "message": {"role": "assistant", "content": response_text},
                    "finish_reason": "stop",
                }
            ],
            "usage": {
                "prompt_tokens": len(prompt.split()),
                "completion_tokens": len(response_text.split()),
                "total_tokens": len(prompt.split()) + len(response_text.split()),
            },
        }


@app.get("/ui", response_class=HTMLResponse)
async def web_ui():
    """Web UI."""
    return """
<!DOCTYPE html>
<html>
<head>
    <title>TurboQuant API</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            padding: 30px;
        }
        h1 { color: #333; margin-bottom: 10px; }
        .subtitle { color: #666; margin-bottom: 30px; }
        .panel {
            background: #f8f9fa;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 20px;
        }
        textarea {
            width: 100%;
            min-height: 100px;
            padding: 12px;
            border: 2px solid #e0e0e0;
            border-radius: 8px;
            font-size: 14px;
            resize: vertical;
        }
        button {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border: none;
            padding: 12px 30px;
            border-radius: 8px;
            font-size: 16px;
            cursor: pointer;
            margin-top: 15px;
        }
        .output {
            background: #1e1e1e;
            color: #d4d4d4;
            padding: 20px;
            border-radius: 8px;
            min-height: 150px;
            white-space: pre-wrap;
            font-family: monospace;
        }
        .stats {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 15px;
            margin-top: 20px;
        }
        .stat-card {
            background: white;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
        }
        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #667eea;
        }
        .stat-label {
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🚀 TurboQuant API</h1>
        <p class="subtitle">OpenAI-compatible API with KV cache compression</p>

        <div class="panel">
            <h3>💬 Chat</h3>
            <textarea id="prompt" placeholder="Enter your message...">What is quantum computing?</textarea>
            <br>
            <button onclick="send()">Send</button>
            <button onclick="clearOutput()">Clear</button>
            <div id="output" class="output" style="margin-top: 20px;">Response will appear here...</div>
        </div>

        <div class="stats" id="stats"></div>
    </div>

    <script>
        async function loadStats() {
            try {
                const r = await fetch('/v1/turboquant/stats');
                const s = await r.json();
                document.getElementById('stats').innerHTML = `
                    <div class="stat-card">
                        <div class="stat-value">${s.compression_ratio.toFixed(1)}x</div>
                        <div class="stat-label">Compression</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">${s.bit_width}-bit</div>
                        <div class="stat-label">Quantization</div>
                    </div>
                    <div class="stat-card">
                        <div class="stat-value">${s.memory_saved_gb.toFixed(1)}GB</div>
                        <div class="stat-label">Memory Saved</div>
                    </div>
                `;
            } catch (e) {
                console.error('Stats error:', e);
            }
        }

        async function send() {
            const prompt = document.getElementById('prompt').value;
            const output = document.getElementById('output');
            output.textContent = 'Thinking...';

            try {
                const r = await fetch('/v1/chat/completions', {
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify({
                        model: 'gemma-4-31b',
                        messages: [{role: 'user', content: prompt}],
                        max_tokens: 100,
                        turboquant_bits: 3,
                        stream: false
                    })
                });
                const data = await r.json();
                output.textContent = data.choices[0].message.content;
                loadStats();
            } catch (e) {
                output.textContent = 'Error: ' + e.message;
            }
        }

        function clearOutput() {
            document.getElementById('output').textContent = 'Response will appear here...';
        }

        loadStats();
    </script>
</body>
</html>
    """


def main():
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()

    # Check for model
    model_paths = [
        Path("models/gemma-4-31b-it-Q2_K.gguf"),
        Path("models/gemma-4-9b-it-Q2_K.gguf"),
    ]
    for p in model_paths:
        if p.exists():
            model_path = p
            print(f"📦 Model found: {model_path}")
            break
    else:
        print("⚠️  No model found - running in demo mode")

    print(f"""
╔══════════════════════════════════════════════════════════════════╗
║                    🚀 TURBOQUANT API SERVER                       ║
╠══════════════════════════════════════════════════════════════════╣
║  API Documentation: http://{args.host}:{args.port}/docs                    ║
║  Web UI:          http://{args.host}:{args.port}/ui                       ║
║  Chat Endpoint:    POST http://{args.host}:{args.port}/v1/chat/completions ║
╚══════════════════════════════════════════════════════════════════╝
    """)

    uvicorn.run(app, host=args.host, port=args.port)


if __name__ == "__main__":
    main()
